# Generated by Django 6.0.6 on 2026-06-11 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicAPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('original_prompt', models.TextField()),
                ('llm_raw_response', models.JSONField()),
                ('active', models.BooleanField(default=True)),
                ('requires_path', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_apis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sys_dynamic_api',
            },
        ),
        migrations.CreateModel(
            name='APIField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('data_type', models.CharField(choices=[('char', 'CharField'), ('text', 'TextField'), ('int', 'IntegerField'), ('float', 'FloatField'), ('bool', 'BooleanField'), ('date', 'DateField'), ('json', 'JSONField')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('max_length', models.IntegerField(blank=True, default=255, null=True)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='engine.dynamicapi')),
            ],
            options={
                'db_table': 'sys_api_field',
                'unique_together': {('api', 'field_name')},
            },
        ),
    ]
