# Generated by Django 6.0.6 on 2026-06-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamicapi',
            old_name='requires_path',
            new_name='requires_auth',
        ),
        migrations.RenameField(
            model_name='dynamicapi',
            old_name='updated_At',
            new_name='updated_at',
        ),
    ]
